<?php

define('ISLANDORA_PREVIEW_HOOK', 'islandora_preview_object');


/**
 * Implements hook_theme().
 */
function islandora_preview_theme($existing, $type, $theme, $path) {
    return array(
        'islandora_preview' => array(
            'file' => 'theme/theme.inc',
            'variables' => array('islandora_object' => NULL),
        ),
        // Default object template.
        'islandora_default_preview' => array(
            'file' => 'theme/theme.inc',
            'template' => 'theme/islandora-preview',
            'variables' => array('islandora_object' => NULL),
        ),
    );
}

/**
 * Renders the default view object page for the given object.
 *
 * @param AbstractObject $object
 *   The object used to render the view object page.
 *
 * @return array
 *   The default rendering of the object view page, indexed at 'Default output'.
 */
function islandora_default_islandora_preview_object($object) {
    $output = theme('islandora_default_preview', array('islandora_object' => $object));
    return array('Default output' => $output);
}

?>
