<?php

/**
 * @file
 * install functionality
 *
 * Contains all install related functionality
 */


/**
 * Implements hook_uninstall().
 */
function arteleku_collection_page_uninstall() {
  // Remove variables.
  $variables = array(
    'arteleku_collection_page_collection_data',
    'arteleku_collection_page_limit',
    'arteleku_collection_page_facet_limit',
  );
  foreach ($variables as $variable) {
    variable_del($variable);
  }}
